# Generated by Django 3.0 on 2019-12-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=100)),
                ('profile_dk', models.CharField(max_length=250)),
                ('profile_ek', models.CharField(max_length=100)),
                ('signup_code', models.CharField(max_length=50)),
                ('unredeemed_invites', models.TextField()),
                ('unsent_invites', models.TextField()),
                ('links', models.IntegerField(default=0)),
            ],
        ),
    ]
