# Generated by Django 3.0 on 2019-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='links',
            new_name='entanglements',
        ),
        migrations.AddField(
            model_name='member',
            name='profileCreated',
            field=models.BooleanField(default=False),
        ),
    ]
