# Generated by Django 3.0 on 2019-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0004_member_nonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nonce',
            new_name='inner_profile_EK',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='entanglements',
            new_name='intersections',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_dk',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_ek',
        ),
        migrations.AddField(
            model_name='member',
            name='inner_profile_DK',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='outer_profile_DK',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='outer_profile_EK',
            field=models.CharField(default='', max_length=100),
        ),
    ]
