# Generated by Django 3.0 on 2019-12-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asamblea', '0005_auto_20191214_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='intersect_requests',
            field=models.TextField(default=''),
        ),
    ]
